services:
  - type: web
    name: 24flightplanner
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
